
CREATE TABLE `user` (
  `USER_NO` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `USER_EMAIL` varchar(100) DEFAULT NULL,
  `USER_PWD` varchar(500) DEFAULT NULL,
  `USER_NM` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `CERT_YN` varchar(1) DEFAULT 'N',
  `SALT` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`USER_NO`),
  UNIQUE KEY `USER_EMAIL_UNIQUE` (`USER_EMAIL`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;
