#port
server:
  port: 9876

#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orz?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: orz
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate # 운영시에는 validate 추천
    show-sql: true
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
    
orz:
  jwt:
    secret: orz1234